[build]
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/generate-itinerary"
  to = "/.netlify/functions/generate-itinerary"
  status = 200

[functions]
  node_bundler = "esbuild"
  
  [functions."generate-itinerary"]
    timeout = 30
